# builder image
FROM golang:1.25-bookworm as builder

WORKDIR /oasys-validator

COPY . .

RUN make geth

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y ca-certificates wget libsnappy-dev libjemalloc-dev
RUN update-ca-certificates

WORKDIR /app

COPY --from=builder /oasys-validator/build/bin /app


EXPOSE 8545 8546 30303 30303/udp

ENTRYPOINT ["/app/geth"]
